name: 'Install Dependencies'
description: 'Install the macOS build dependencies via Homebrew'
author: 'Mumble Developers'

runs:
    using: "composite"
    steps:
        - run: '$GITHUB_ACTION_PATH/main.sh'
          shell: bash
