#!/usr/bin/env python3
#
# Copyright The Mumble Developers. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file at the root of the
# Mumble source tree or at <https://www.mumble.info/LICENSE>.

from typing import Optional

import argparse
import re
import os

varNameIdx = 0
filePathIdx = 1
displayNameIdx = 2
urlIdx = 3
defineGuardIdx = 4

repoRoot = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))

# List of (3rdparty) licenses  [<variableName>, <pathToLicenseFile>, <DisplayName>, <URL>, (<define-guard>)?]
licenses = [
    ["licenseMumble", "LICENSE", "Mumble", "https://www.mumble.info/"],
    ["licenseQt", "3rdPartyLicenses/qt_license.txt", "Qt", "https://www.qt.io/"],
    ["licenseOpenSSL", "3rdPartyLicenses/openssl_license.txt", "OpenSSL", "http://www.openssl.org/"],
    ["licenseProtobuf", "3rdPartyLicenses/protobuf_license.txt", "Protobuf", "https://protobuf.dev/"],
    ["licensePoco", "3rdPartyLicenses/poco_license.txt", "POCO C++ Libraries", "https://pocoproject.org/"],
    ["licenseBoost", "3rdPartyLicenses/boost_license.txt", "Boost C++ Libraries", "https://www.boost.org/"],
    ["licenseOpus", "3rdPartyLicenses/opus_license.txt", "Opus", "https://opus-codec.org/"],
    ["licenseLibsndfile", "3rdPartyLicenses/libsndfile_license.txt", "libsndfile", "http://www.mega-nerd.com/libsndfile/"],
    ["licenseOgg", "3rdPartyLicenses/libogg_license.txt", "libogg", "http://www.xiph.org/"],
    ["licenseVorbis", "3rdPartyLicenses/libvorbis_license.txt", "libvorbis", "http://www.xiph.org/"],
    ["licenseFLAC", "3rdPartyLicenses/libflac_license.txt", "libFLAC", "http://flac.sourceforge.net/"],
    ["licenseSPEEXDSP", "3rdparty/speexdsp/COPYING", "SpeexDSP", "http://www.speex.org/"],
    ["licenseRnnoise", "3rdparty/rnnoise-src/COPYING", "RNNoise", "https://github.com/xiph/rnnoise"],
    ["licenseQtTranslations", "src/mumble/qttranslations/LICENSE",
        "Additional Qt translations", "https://www.virtualbox.org/ticket/2018"],
    ["licenseFlagIcons", "3rdparty/flag-icons/LICENSE", "flag-icons", "https://flagicons.lipis.dev/" ],
    ["licenseQQBonjour", "3rdparty/qqbonjour/LICENSE", "QQBonjour", "https://doc.qt.io/archives/qq/qq23-bonjour.html"],
    ["licenseSmallFT", "3rdparty/smallft/LICENSE", "smallft", "https://www.xiph.org"],
    ["licenseCLI11", "3rdparty/CLI11/LICENSE", "CLI11", "https://github.com/CLIUtils/CLI11"],
    ["licenseNlohmannJson", "3rdparty/nlohmann_json/LICENSE.MIT", "nlohmann/json", "https://github.com/nlohmann/json"],
    ["licenseSpdlog", "3rdparty/spdlog/LICENSE", "spdlog", "https://github.com/gabime/spdlog"],
    ["licenseTracy", "3rdparty/tracy/LICENSE", "Tracy Profiler", "https://github.com/wolfpld/tracy"],
    ["licenseUtfCpp", "3rdparty/utfcpp/LICENSE", "utfcpp", "https://github.com/nemtrif/utfcpp"],
    ["licenseOldStyleLicenseHeaders", "3rdPartyLicenses/mumble-old-license-headers/LICENSE.txt", "Old-style Mumble license headers", "https://www.mumble.info"],
    ["licenseArc4RandomUniform", "3rdparty/arc4random/LICENSE", "arc4random_uniform", "https://www.openbsd.org"],
]


def formatLicenseVar(var_name: str, license_path: str, define_guard: Optional[str]) -> str:
    with open(os.path.join(repoRoot, license_path), "r") as file:
        content = file.read().strip().replace("\"", "\\\"")

        content = "\"" + re.sub("\\n\\s*", "\\\\n\"\n\t\"", content) + "\""

        content = "static const char *" + var_name + " = " + content + ";"

        if define_guard:
            content = "#ifdef " + define_guard + "\n" + content + "\n" + "#endif // " + define_guard + "\n"

        return content


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", help="Path to the file to which the generated code shall be written." +
                        " If none is given, the content is written to stdout", metavar="PATH")

    args = parser.parse_args()

    content = """/*
 * This file was auto-generated by scripts/generate_license_header.py
 * DO NOT EDIT IT MANUALLY
 */
#ifndef MUMBLE_LICENSES_H_
#define MUMBLE_LICENSES_H_

struct ThirdPartyLicense {
	const char* name;
	const char* url;
	const char* license;

	ThirdPartyLicense() : name(nullptr), url(nullptr), license(nullptr) {}
	ThirdPartyLicense(const char* name_, const char* url_, const char* license_)
	    : name(name_), url(url_), license(license_) {}

	bool isEmpty() const { return !name && !url && !license; }
};
"""
    
    for currentLicense in licenses:
        content += "\n" + formatLicenseVar(var_name=currentLicense[varNameIdx], license_path=currentLicense[filePathIdx],
                define_guard=currentLicense[defineGuardIdx] if len(currentLicense) > defineGuardIdx else None)


    content += "\n\n"
    content += "static const ThirdPartyLicense licenses3rdParties[] = {\n"

    for currentLicense in licenses[ 1 : ]:
        if len(currentLicense) > defineGuardIdx:
            content += "#ifdef " + currentLicense[defineGuardIdx] + "\n"

        content += "\t" + ("ThirdPartyLicense(\"%s\", \"%s\", %s)" % (currentLicense[displayNameIdx], currentLicense[urlIdx],
            currentLicense[varNameIdx])) + ",\n"

        if len(currentLicense) > defineGuardIdx:
            content += "#endif //" + currentLicense[defineGuardIdx] + "\n"

    content += "\t// Empty entry that marks the end of the array\n"
    content += "\tThirdPartyLicense()\n"
    content += "};\n"
    content += "#endif // MUMBLE_LICENSES_H_\n"

    if args.output:
        with open(args.output, "w") as outFile:
            outFile.write(content)
    else:
        print(content)


if __name__ == "__main__":
    main()
